// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  about_me: defineAsyncComponent(() => import("./AboutMe/index.vue")),
  card: defineAsyncComponent(() => import("./Card/index.vue")),
  connection: defineAsyncComponent(() => import("./Connection/index.vue")),
  contacts: defineAsyncComponent(() => import("./Contacts/index.vue")),
  school: defineAsyncComponent(() => import("./School/index.vue")),
  services: defineAsyncComponent(() => import("./Services/index.vue")),
  welcome: defineAsyncComponent(() => import("./Welcome/index.vue")),
});
